name: CICD pipeline

on:
  workflow_dispatch:

jobs:
  first-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Hello GitHub Actions
        run: echo "CI Pipeline is working successfully!"